Fix/content readthedocs3
rl-institut/offgridders pull request #125
Opened 2020-08-18 13:25 UTC by santiagoinfantinom

3rd part of the readthedocs correction

2020-08-19 11:12 UTC, santiagoinfantinom commented on docs/Stability.rst
>  **to be updated**
Should we leave this kind of comments?

2020-08-19 11:17 UTC, santiagoinfantinom commented on docs/Stability.rst
> +* In case of later on grid-interconnected micro grids, the stability criteria has to adhered to the off-grid operation
Was this interpretation correct?

2020-08-19 11:18 UTC, santiagoinfantinom commented on docs/Validity.rst
> +(-> But I need to adjust stability constraint again, as this locks pcc consumption directly to constraint, <->  it only HAS TO BE POSSIBLE to consume from grid. Assuming this is the definition.
Was this some sort of Padnote for you to remember?

2020-08-19 11:19 UTC, santiagoinfantinom commented on docs/Validity.rst
> +(-> But I need to adjust stability constraint again, as this locks pcc consumption directly to constraint, <->  it only HAS TO BE POSSIBLE to consume from grid. Assuming this is the definition.
And Later at Line 23 there are open categories with nothing in it. What should be in there?

2020-08-19 12:56 UTC, smartie2076 commented on docs/Stability.rst
>  **to be updated**
> Should we leave this kind of comments?

you could delet them in the rat and gather them in the overarching issue, in a checklist so that we do not forget them. You can also add the instances, where there is a link to a non-existent example, eg. The examples. Could look like this:

- [ ] information in file xy, stability constraints, needs to be updated
- [ ] section examples in file xy is missing content

2020-08-19 12:59 UTC, smartie2076 commented on docs/Validity.rst
> +(-> But I need to adjust stability constraint again, as this locks pcc consumption directly to constraint, <->  it only HAS TO BE POSSIBLE to consume from grid. Assuming this is the definition.
> Was this some sort of Padnote for you to remember?

Yes, it can be deleted

2020-08-19 13:00 UTC, smartie2076 commented
Sorry, on my phone I can not read everything easily, so just a few answers.

2020-08-19 13:17 UTC, santiagoinfantinom commented on docs/Stability.rst
>  **to be updated**
I created Issue #130 for this

2020-08-19 15:41 UTC, smartie2076 reviewed
I think you have removed a key that is used for formatting cursive ("\_").

Are you checking if the readthedocs compiles correctly, locally with "build html" or online?

2020-08-19 15:41 UTC, smartie2076 commented on docs/Components.rst
> +    Creates fuel source "source_fuel" for OEM, including variable costs (based on fuel price and combustion value) and renewable share. ATTENTION: May this lead to infeasible OEM, if generator has mi
```suggestion
    Creates fuel source "source_fuel" for OEM, including variable costs (based on fuel price and combustion value) and renewable share. 
```
Hm, the whole page is not very beneficial for users (and not programmers) of Offgridders. Can you add this in l. 4: "For a deep insight into Offgridders energy system model, the components are presented below. This information is mainly important for developers, that are thinking of changing module `G` (especially `G0` and `G2a`.)."

You can actually copy some of these definitions to the docstrings of G2a when you are there, and then maybe we can delete the page. Maybe.

2020-08-19 15:41 UTC, smartie2076 commented on docs/Components.rst
> +* **fuel_fix** (_micro_grid_system, bus_fuel, experiment):
Doesnt "\_" make it a cursive on the readthedocs? For that, "\_" has to be in front of the cursive text and at its end. You delete only one part of it...

2020-08-19 15:41 UTC, smartie2076 commented on docs/Cost.rst
> +In this list, the costs of grid extension, local distribution grid and project costs are not specified by variable investment costs.Furthermore, project investment costs do not have a specified lifet
```suggestion
In this list, the costs of grid extension, local distribution grid and project costs are not specified by variable investment costs. 
```
Actually, there is a lifetime of the project costs (eg. connection costs), so the sentence needed to be deleted.

2020-08-19 15:41 UTC, smartie2076 commented on docs/Stability.rst
> +* In case of later on grid-interconnected micro grids, the stability criteria has to adhered to the off-grid operation
```suggestion
* In case of later-on grid-interconnected micro grids, the stability criteria has to adhered to by the during off-grid operation of the MG. 
```

2020-08-19 15:41 UTC, smartie2076 commented on docs/Stability.rst
> +* In case of later on grid-interconnected micro grids, the stability criteria has to adhered to the off-grid operation
See suggestion

2020-08-19 15:47 UTC, smartie2076 commented
Actually, you still need to update the changelog!

2020-08-25 09:59 UTC, santiagoinfantinom commented on docs/Components.rst
> +* **fuel_fix** (_micro_grid_system, bus_fuel, experiment):
Ohh I didn't know the goal was to make the variables as cursives. Now that I look at other readthedocs I realize that is the way its done. I'm creating another commit making the variables italic.

2020-08-25 12:10 UTC, santiagoinfantinom commented on docs/Components.rst
> +    Creates fuel source "source_fuel" for OEM, including variable costs (based on fuel price and combustion value) and renewable share. ATTENTION: May this lead to infeasible OEM, if generator has mi
I'm not sure about deleting the page. I don't really know where some of the components are define, but I find it always helpful to have this sort of information in the readthedocs :)

2020-08-25 12:11 UTC, santiagoinfantinom commented on docs/Components.rst
> +* **genset_oem** (*micro_grid_system, bus_fuel, bus_electricity_mg, experiment*):
After this, I realized one could apply italic to the whole line, that's why there different

2020-08-25 12:14 UTC, santiagoinfantinom reviewed
@smartie2076 I took care of your comments and added some of the lines in the Components.rst to the code itself in G2a. Added the changes in the CHANGELOG

2020-08-31 10:45 UTC, santiagoinfantinom commented
@smartie2076 Merge conflicts resolved. After your review, Ill merge it :)

2020-08-31 13:24 UTC, smartie2076 requested changes

2020-08-31 13:24 UTC, smartie2076 commented on CHANGELOG.md
> +- Added some Docstrings to functions in G2a
```suggestion
- Added some docstrings to functions in `G2a`, copied from `Components.rst` (#125)
```

2020-08-31 13:24 UTC, smartie2076 commented on docs/Components.rst
> +For a deep insight into Offgridders energy system model, the components are presented below. This information is mainly important for developers, that are thinking of changing module G (especially G0
```suggestion
For a deep insight into Offgridders energy system model, the components are presented below. This information is mainly important for developers that are thinking of changing module `G` (especially `G0` and `G2a`), eg. when adding new assets.
```

2020-08-31 13:24 UTC, smartie2076 commented on docs/Components.rst
> +    Generates fossi-fueled genset "transformer_fuel_generator" for OEM with generator efficiency, investment and variable costs.
```suggestion
    Generates fossil-fueled genset "transformer_fuel_generator" for OEM with generator efficiency, investment and variable costs.
```

2020-08-31 13:24 UTC, smartie2076 commented on docs/Stability.rst
> +(5) https://www.solarwirtschaft.de/fileadmin/user_upload/Session1_4_Intersolar_ARE_event.pdf
All lines from l. 19 to 31 should be deleted (starting with "First documents to be red"

2020-08-31 13:24 UTC, smartie2076 commented on src/G2a_oemof_busses_and_componets.py
> +    """
Please check again - this generator does not have a min load and nonconvex flow and does not fit the docstrings. Components.rst lalso needs to be updated. The docstrings describes `genset_fix_minload()` below.

2020-09-01 13:18 UTC, smartie2076 approved these changes

2020-09-01 13:18 UTC, merged