Change "Yes" to True
rl-institut/offgridders pull request #127
Opened 2020-08-18 13:31 UTC by santiagoinfantinom

Fix #114

2020-08-18 14:17 UTC, santiagoinfantinom commented
@santiagoinfantinom  Check Xslx for "Yes" and "No"

2020-08-19 08:51 UTC, santiagoinfantinom commented
Changed the xlsx file and the code. Ready to merge

2020-08-31 13:14 UTC, smartie2076 requested changes
@santiagoinfantinom please also edit the Changelog.md for this PR.

2020-08-31 14:02 UTC, smartie2076 approved these changes

2020-09-01 07:04 UTC, merged