Feature critical demand
rl-institut/offgridders pull request #166
Opened 2021-12-01 12:39 UTC by adnanalakori

Just re-define constants..

2021-12-01 16:55 UTC, adnanalakori reviewed
I am not sure about this commit!

2021-12-02 12:39 UTC, smartie2076 commented
> Just re-define constants.. Fixes #165

Hi @adnanalakori! I am not sure from the title and text what you are planning in this PR, and will have to check this from the code. You should try to use a title that is different from #165, that directly tells me what you do.

Also, "fix"/"close" are github-specific words that imply an action that github will take. They are used to close issues, ie. to adress and solve an issue. Used here, I am not sure what it will do with the other PR.

> By the way: once I made a PR, it shows with a new number #166 -> should be a way to keep this PR within the previous one #165?

I think you created a new PR, because you pushed to a different branch name. The other branch is `feature_critical_demand` and not `feature_critical_demand_`. If you want to continue working on #165 you need to push onto `feature_critical_demand`!

Should I then even look at this?

2021-12-02 12:44 UTC, smartie2076 requested changes
`cbc.exe` and `coin-license.txt` should not be pushed to the repo. I am not clear what you are planning to do...

2021-12-02 12:44 UTC, smartie2076 commented on src/constants.py
> +DEMAND_DC = "demand_dc_critical"
You now have redefined `DEMAND_AC` and `DEMAND_DC` directly after you defined it. Variables have to be unique.

2021-12-02 12:44 UTC, smartie2076 commented on src/constants.py
> +TITLE_DEMAND_DC = "title_demand_dc_critical"
`TITLE_DEMAND_AC` and `TITLE_DEMAND_DC` are defined twice, this does not work.

2021-12-02 12:44 UTC, smartie2076 commented on src/G2a_oemof_busses_and_componets.py
> +def demand_ac(micro_grid_system, bus_electricity_ac, demand_profile, demand_name):
What are you planning to do with `demand_name`?

2021-12-02 12:44 UTC, smartie2076 commented on src/G2a_oemof_busses_and_componets.py
> +    demand_name.add(sink_demand_ac)
I do not understand what you use `demand_name` for, and why you use `add()`.

2021-12-02 13:25 UTC, adnanalakori commented
> Should I then even look at this?

Hi @smartie2076, sorry it just a mistake that a slash `_ `was added to the  `feature_critical_demand`, then a new PR has been opened, I was wondering of that :-) Could we delate this PR completely?

2021-12-02 13:28 UTC, adnanalakori commented on src/constants.py
> +DEMAND_DC = "demand_dc_critical"
Ok, got it, w'll correct it

2021-12-02 13:42 UTC, adnanalakori commented on src/G2a_oemof_busses_and_componets.py
> +    demand_name.add(sink_demand_ac)
> 
I was just planning just to merge the functions `generate.demand_ac` and `generate.demand_dc` to function `generate.demand`, but not sure about the structure of this function below: 
https://github.com/rl-institut/offgridders/blob/a8fa6f1a6b8319962e65505320f9b47267fbef0a/src/G2a_oemof_busses_and_componets.py#L704

2021-12-03 08:26 UTC, adnanalakori commented on src/constants.py
> +TITLE_DEMAND_DC = "title_demand_dc_critical"
> `cbc.exe` and `coin-license.txt` should not be pushed to the repo. I am not clear what you are planning to do...

I don't know how `cbc.exe` was pushed, weird...! I just received an error message that `cbc.exe` was not found, then I copied it again to offgridders folder and re-run it.

2021-12-06 09:07 UTC, closed without merging

2021-12-08 14:53 UTC, smartie2076 commented on src/G2a_oemof_busses_and_componets.py
> +    demand_name.add(sink_demand_ac)
> I was just planning just to merge the functions generate.demand_ac and generate.demand_dc to function generate.demand, but not sure about the structure of this function below

Yeah, that is a good idea! You will have to change

`def demand(micro_grid_system, bus_electricity_ac, demand_profile, demand_name):`

> Also, just trying to reach your goal mentioned in the #162, that the new demand shall be like that :
> [Code]

This is correct :)

2021-12-08 14:54 UTC, smartie2076 commented on src/G2a_oemof_busses_and_componets.py
> +def demand_ac(micro_grid_system, bus_electricity_ac, demand_profile, demand_name):
Now I understand it is correct.

2021-12-08 14:56 UTC, smartie2076 commented on src/constants.py
> +TITLE_DEMAND_DC = "title_demand_dc_critical"
Yeah, when you commit, by default all changes and added files will be added to your commit. You have to unselect the file from the upper box (the one over the commit message box):

![grafik](https://user-images.githubusercontent.com/44204527/145230223-3d0ca631-d245-4f91-a357-94217cc6b337.png)

2021-12-08 14:57 UTC, smartie2076 commented on src/constants.py
> +DEMAND_DC = "demand_dc_critical"
Will run without errors, but not nesessarily run as intendet :D